#!/bin/bash
#SBATCH --job-name=lammps
#SBATCH --output=lammps
#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --mem-per-cpu=1800M
#SBATCH --time=48:00:00
echo "Job started at `date`"

module load lammps-omp/20170811

srun lmp_icc_openmpi < thoria_sig5_tilt_xe_74.in

echo "Job finished at `date`"#!/bin/bash
