#Use with 2D geometry option only
[options]
name = "octagon_"
weak_collision_order = 0
num_threads = 4

[material_parameters]
energy_unit = "EV"
mass_unit = "AMU"
Eb = [ 0.0, 0.0,]
Es = [ 5.76, 0.0,]
Ec = [ 1.0, 1.0,]
Z = [ 5, 7,]
m = [ 10.811, 14,]

[particle_parameters]
length_unit = "ANGSTROM"
energy_unit = "EV"
mass_unit = "AMU"
N = [ 1000  ]
m = [ 1.008 ]
Z = [ 1 ]
E = [ 5000.0 ]
Ec = [ 1.0 ]
Es = [ 10.0 ]
pos = [ [ 0.0, 0.0, 0.0,] ]
dir = [ [ 0.9999999999984769, 1.7453292519934434e-6, 0.0,] ]

[geometry_input]
length_unit = "ANGSTROM"
points = [
	[    0.0,      0.0],
	[ 1000.0,      0.0],
	[  707.1,    707.1],
	[    0.0,   1000.0],
	[ -707.1,    707.1],
	[-1000.0,      0.0],
	[ -707.1,   -707.1],
	[    0.0,  -1000.0],
	[  707.1,   -707.1],
]
boundary = [1, 2, 3, 4, 5, 6, 7, 8]
triangles = [
	[0, 1, 2],
	[0, 2, 3],
	[0, 3, 4],
	[0, 4, 5],
	[0, 5, 6],
	[0, 6, 7],
	[0, 7, 8],
	[0, 8, 1],
]
simulation_boundary_points = [ [ -1100.0, -1100.0,], [ -1100.0, 1100.0,], [ 1100.0, 1100.0,], [ 1100.0, -1100.0,],]
densities = [
	[0.065, 0.065],
	[0.065, 0.065],
	[0.065, 0.065],
	[0.065, 0.065],
	[0.065, 0.065],
	[0.065, 0.065],
	[0.065, 0.065],
	[0.065, 0.065],
]
electronic_stopping_correction_factors = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
energy_barrier_thickness = 2.5
