#Use with SPHEREINCUBOID geometry option only
[options]
name = "ballbox_"
track_trajectories = false
track_recoils = true
track_recoil_trajectories = false
track_displacements = true
track_energy_losses = false
num_threads = 8
num_chunks = 10
electronic_stopping_mode = "INTERPOLATED"
mean_free_path_model = {"THRESHOLD"={density=1.5e28}}

[material_parameters]
energy_unit = "EV"
mass_unit = "AMU"
Eb = [1.30, 1.07, 0.0]
Es = [5.27, 5.32, 0.0]
Ec = [1.0, 1.0, 1.0]
Ed = [35.6, 54.3, 0.0]
Z = [92, 42, 54]
m = [238.0, 95.95, 134.0]

[particle_parameters]
length_unit = "ANGSTROM"
energy_unit = "EV"
mass_unit = "AMU"
N = [100, 0]
m = [97.0, 136.0]
Z = [39, 53]
E = [101.3e6, 74.6e6]
Ec = [1.0, 1.0]
Es = [3.58, 3.63]
pos = [[-1640.0, 0.0, 0.0], [-1640.0, 0.0, 0.0]]
dir = [
	[0.9999999999984769, 1.7453292519934434e-6, 0.0],
	[0.9999999999984769, 1.7453292519934434e-6, 0.0]
]

[geometry_input]
length_unit = "ANGSTROM"

sphere_radius = 640.0
sphere_densities = [0.0, 0.0, 0.00327]
sphere_electronic_stopping_correction_factor = 1.0

cuboid_corners = [[-1641.0, -1641.0, -1641.0], [1641.0, 1641.0, 1641.0]]
cuboid_densities = [0.039, 0.011, 0.0]
cuboid_electronic_stopping_correction_factor = 1.0
